<? require ('templates/header.php'); ?>
<title>Understanding the Iran-Contra Affairs - The Iran-Contra Affairs</title>
</head>
<? require ('templates/irancontrabanner.php'); ?>
    
<div style="margin: 10px 0px 0px 20px; width: 550px" align="justify" id="welcomenote">
<h2>Nicaragua's Background</h2>
<p><strong>Background of U.S. Policy</strong><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; The United States has long had an interest in the political developments of Latin America, due to the region's close proximity.&nbsp; Numerous presidents have fashioned policies in an attempt to ensure that U.S. interests in the region are protected.&nbsp; Most notably, perhaps, President James Monroe established the “Monroe Doctrine” in 1823, a policy stating that the United States would prevent European intervention in Latin America. The Roosevelt Corollary to the Monroe Doctrine, established by Theodore Roosevelt, asserted the right of the United States to intervene militarily in Latin America.&nbsp; Often, these interventions had the ostensible aim of instituting democracy in the region.&nbsp; In 1933, President Franklin D. Roosevelt's Good Neighbor Policy declared that the U.S. would no longer intervene in Latin America (with certain exceptions) and would recognize governments in the region regardless of their form. President John F. Kennedy established the Alliance for Progress, which sought to institute democracy and development in the region in response to the perceived threat of Cuban- and Soviet-backed socialism.&nbsp; This policy waned under the Nixon administration but was reemphasized after the Vietnam War by Congress and President Carter, who both sought to advance human rights in Latin America through means other than intervention.&nbsp; As we shall see, while President Reagan ostensibly espoused similar goals, his tactics differed from President Carter's.</p>
<p><strong>The Rise of the Somoza Dynasty</strong><br />
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; As the history of U.S. policy toward Latin America suggests, the United States has long intervened in Nicaraguan affairs.&nbsp; U.S. troops often intervened in the country in the early 20th century.&nbsp; In 1912, the Conservative Adolfo Díaz took power.&nbsp; Liberals subsequently revolted, and the Untied States sent marines to suppress the rebellion.&nbsp; In 1924, the Liberal Juan Sacasa won the Nicaraguan presidency but was overthrown by Emiliano Chamorro, a Conservative.&nbsp; The United States forced him to resign but then recognized Adolfo Díaz as the next president.&nbsp; This prompted a Liberal rebellion; among those Liberals who fought in the revolt were José Maria Moncada, Augusto César Sandino, and Anastasio Somoza García.&nbsp; The United States eventually sent in marines to support Díaz until the election in 1928, which Moncada won.&nbsp; Sandino, however, did not support Moncada and continued fighting.&nbsp; Partially as a result of Sandino's destabilizing presence, the United States trained the Nicaraguan National Guard.&nbsp; In the 1932 elections, Juan Sacasa became president.&nbsp; Prior to his departure, Moncada made Anastasio Somoza García the head of the National Guard, a choice supported by the United States.&nbsp; Sandino reached a deal with the government to maintain an army and control over a patch of land in Nicaragua,  but Somoza's National Guard killed Sandino in 1934.&nbsp; Despite Sacasa's request for U.S. help, the United States under FDR failed to intervene as Somoza seized power in 1936, and his dictatorial dynasty ruled Nicaragua for the next 43 years.</p>
<p><strong>Anastasio Somoza Debayle and the Revolution</strong><br />
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In 1967, Anastasio Somoza Debayle, the son of Somoza García, became president.&nbsp; He was widely disliked in Nicaragua, as he suppressed oppositional elements and enriched himself while in power.&nbsp; In 1972, an earthquake rocked Managua, Nicaragua's capital, and Somoza exercised “emergency powers” to deal with the earthquake while he and his colleagues stole a majority of international aid sent to Nicaragua in the earthquake's wake.&nbsp; In 1974, the socialist Sandinista National Liberation Front (FSLN) <strong>[link to Sandinista Content here]</strong> staged a kidnapping of Nicaraguan elites at a Christmas Party.&nbsp; In response, Somoza declared a state of siege and engaged in a brutal crackdown marked by serious human rights violations against guerrillas and peasants.&nbsp; In the United States, where Somoza Debayle had largely been ignored, politicians sought to induce reform in Nicaragua because of its poor human rights record, a trend that continued with the election of President Jimmy Carter in 1977. <br />
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Nicaraguan businessmen sought reforms as well, as the regime's policies were inconsistent with private-sector interests.&nbsp; In 1974, Pedro Joaquín Chamorro, a popular Nicaraguan politician, founded the Union for Democratic Liberation (UDEL), an opposition party supported by Alfonso Robelo (a cottonseed oil manufacturer) and Adolfo Calero (a Conservative politician and manager of a bottling factory).&nbsp; The Sandinistas, too, continued to oppose the regime, beginning with more attacks in 1977.&nbsp; In January 1978, Chamorro was assassinated, which led to widespread protests against the regime despite the fact that the assassins were never conclusively identified.&nbsp; The Sandinistas continued to fight the regime, and with support from Costa Rica, Venezuela, Panama, and Cuba, they were increasingly successful.&nbsp; By summer 1979, the United States decided that Somoza's rule was no longer tenable in Nicaragua and, along with other Latin American leaders, sought to moderate the new Nicaraguan government that would inevitably come to power.&nbsp; The Sandinistas paid lip service to this request.&nbsp; On July 19, 1979, the Sandinistas seized power in Nicaragua.</p>
<p><strong>Post-Revolution Developments </strong><br />
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; After the Marxist-Leninist Sandinistas took power, they imposed a state of emergency and nationalized various sectors of the economy, expropriated land and businesses from those with ties to the old regime, and reorganized Nicaraguan political life.&nbsp; In an attempt to prevent the Sandinistas from forming ties with the Soviet Union and Cuba, the Carter Administration sent aid to the new regime.&nbsp; The Sandinistas nevertheless allied themselves with the Cubans and Soviets; in fact, Cuban military officials advised the Sandinistas after the revolution, and the Sandinistas signed agreements with Moscow in March of 1980.&nbsp; Carter continued to give aid to Nicaragua even as it was discovered that the Sandinistas were sending weapons to Salvadoran rebels. After failed appeals by the Carter and Reagan Administrations to the Sandinistas to cease arms trafficking, Reagan ended all aid to Nicaragua.&nbsp; With the Sandinistas still sending arms to El Salvador, Reagan issued an intelligence finding authorizing the CIA to engage in covert action by funding the contras, ostensibly to support the interdiction of arms going to El Salvador.&nbsp; However, the goal of covert action arguably expanded to include the overthrow of the Sandinistas. It is this framework that eventually led to the Contra half of the Iran-Contra affair.</p>
<p><strong>Contras</strong><br />
  <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong>Soon after the Sandinistas seized power, some segments of Nicaraguan society felt disenchanted with the new regime's policies and sought to bring about change through armed rebellion.&nbsp; These counterrevolutionaries, or “contras,” came to be supported by the United States.&nbsp; Many of the contras were former National Guardsmen under Somoza.&nbsp; Moreover, many contras were peasants and farmers who objected to Sandinista land policies and took up arms against the Sandinistas. Members of the elite and business owners opposed the FSLN's economic policies and repressive measures and fought the regime as well.&nbsp; Most notably, José Francisco Cardenal, the former president of the Chamber of Construction, and Enrique Bermúdez, a former colonel in the National Guard, founded the Nicaraguan Democratic Revolutionary Alliance, which later came to be called the Nicaraguan Democratic Force (FDN).&nbsp; The FDN was the major group of contras supported by the Administration of President Ronald Reagan.</p>
<div>
  <div id="edn"></div>
  <div id="edn"> </div>
</div>
</div>

<? require ('templates/footer.php'); ?>