<? require ('templates/header.php'); ?>
<title>Understanding the Iran-Contra Affairs - The Iran-Contra Affairs</title>
</head>
<? require ('templates/irancontrabanner.php'); ?>

<div style="margin: 10px 0px 0px 20px; width: 760px" align="justify" id="welcomenote">
<div align="left" class="bread_crumbs"><a href="index.php">Home</a> &raquo;  <a href="iran-contra-affairs.php">The Iran Contra Affairs</a> &raquo;  Nicaragua: Background</div>
<h2><a name="headertop" id="headertop"></a><br />Nicaragua</h2>
<div style="margin: 0px 0px 0px 20px">
<p><strong>Background of U.S. Policy in Latin America and the Rise of the Somoza Dynasty in Nicaragua</strong>
  <br /><br />
  The United States has long had an interest in the political developments of Latin America due to the region’s close proximity.  Numerous presidents have fashioned policies in an attempt to ensure that U.S. interests in the region are protected. Most notably, perhaps, President James Monroe established the “Monroe Doctrine” in 1823, a foreign policy stating that the United States would prevent European intervention in Latin America. The Roosevelt Corollary to the Monroe Doctrine, established by President Theodore Roosevelt, asserted the United States’ right to military intervention in Latin America. Often, these interventions were justified with the aim of instituting democracy in particular countries, yet they often included ulterior motives that allowed U.S. presence and power to cement itself within the region  While the Roosevelt Corollary to the Monroe Doctrine was established to manage the region through hard power rather than simple diplomacy, U.S. policymakers quickly learned that the rising economic nationalist movements in Latin America were a force to be reckoned with.
  <br /><br />
  This was particularly exemplified through the Nicaraguan rebellion led by Augusto Sandino between 1927 and 1933. In 1912, the Conservative Adolfo Díaz took power. Liberals subsequently revolted and the United States sent marines to suppress the rebellion. In 1924, the Liberal Juan Sacasa won the Nicaraguan presidency but was overthrown by Emiliano Chamorro, a Conservative. The United States forced him to resign but then recognized Adolfo Díaz as the next president. This prompted a Liberal rebellion; among those Liberals who fought in the revolt were José Maria Moncada, Augusto César Sandino, and Anastasio Somoza García. The United States eventually sent in marines to support Díaz until the election in 1928, which Moncada won. Sandino, however, did not support Moncada and continued fighting. Partially as a result of Sandino’s destabilizing presence, the United States trained the Nicaraguan National Guard. Sandino’s hit-and-run guerilla war tactics, which allowed the rebellion to fight the U.S. Marines in Nicaragua to a draw, further taught the U.S. that political nationalism was an equally powerful force and that attempts to counter it with increased militarism would only lead to a deterioration of American influence.<sup><a href="#footnote1">1</a></sup>
  <br /><br />
  In the 1932 Nicaraguan elections, Juan Sacasa became president. Prior to his departure, Moncada made Anastasio Somoza García the head of the National Guard, a choice supported by the United States. Sandino reached a deal with the government to maintain an army and control over a patch of land in Nicaragua, but Somoza’s National Guard killed Sandino in 1934. Despite Sacasa’s request for U.S. help, the United States under President Franklin Rooselvelt failed to intervene as Somoza seized power in 1936, and his dictatorial dynasty ruled Nicaragua for the next 43 years.
  <br /><br />
  The 1930s Nicaraguan insurgency helped catalyze a larger Latin American backlash against U.S. militarism and Washington’s dollar diplomacy, which was a form of American foreign policy used to further its aims in Latin America and East Asia through use of its economic power by guaranteeing conditional loans. That backlash spurred a new thinking among politicians and foreign policy intellectuals that Washington could no longer afford to play catch-up diplomacy and waste its time responding to continual emergencies either caused or inflamed by direct armed interventions.<sup><a href="#footnote2">2</a></sup> After thirty military expeditions in the span of a few decades had not only failed to pacify Central America and the Caribbean, but had heated passions even further, there began talk of being a “good neighbor” to Latin America as well as to draw down U.S. military ambitions in the region, including Nicaragua.<sup><a href="#footnote3">3</a></sup>
  <br /><br />
  In 1933, President Franklin Roosevelt’s Good Neighbor Policy declared that the U.S. would no longer intervene in Latin America (with certain exceptions) and would recognize governments in the region regardless of their form. This policy continued into and past World War II, which drew the U.S.’ attention towards Europe. After World War II concluded in 1945, Latin America proved willing to give up a degree of sovereignty and allow for U.S. cooperation due to the promise of “exporting democracy” abroad.
  <br /><br />
  President Eisenhower engaged in a South American tour in 1960 with the intention of developing an “Inter-American System” of mutual security. President Eisenhower’s mission was to build up a fund of good will to facilitate inter-American economic cooperation.<sup><a href="#footnote4">4</a></sup> For the U.S., Latin America may not have been the most politically important or most economically profitable region, yet the hemispheric alliance system provided a working blueprint – a model that U.S. diplomatic, intellectual, and military leaders followed to extend channels of authority and corporations used to establish chains of production, finance, and markets elsewhere in the world.<sup><a href="#footnote5">5</a></sup> It was a flexible system of extraterritorial administration, one that allowed the United States, in the name of fighting Communism and promoting development, to structure the internal political and economic relations of allied countries in ways that allowed it to accrue power and exercise effective control over the supply of primary resources – all free from the burden of formal colonialism.<sup><a href="#footnote6">6</a></sup>
  <br /><br />
  Yet the goodwill that established this “Inter-American System” quickly diminished as Latin American reformers and nationalists pushed harder to make good on the promise of democracy and development offered by Allied victory in World War II. Starting in 1944, reform swept the continent, revitalizing old democracies in Chile and Colombia, among other places, and creating new ones in countries such as Guatemala, Peru, Argentina, and Venezuela. Within two years, every Latin American country save Nicaragua, El Salvador, Honduras, Paraguay, and the Dominican Republic was operating under constitutional rule. Broad coalitions ranging from political liberals to Communists toppled dictators throughout the continent, while new reform governments expanded access to social welfare programs.<sup><a href="#footnote7">7</a></sup> The U.S. at first backed this process of democratization, but in 1947 Washington began to send signals that its preference for democrats over autocrats was now contingent on political stability within the region.<sup><a href="#footnote8">8</a></sup> Support for dictators like Nicaragua’s Anastasio Somoza or Dominican Republic’s Rafael Trujillo was no longer understood as the unwanted consequence of intervention. Rather, as a backdrop against subversion, such support was now understood to be the centerpiece of U.S. policy toward Latin America.<sup><a href="#footnote9">9</a></sup>
  <br /><br />
  One reason for this turnaround was the Cold War. Washington found that it greatly preferred anti-Communist dictatorships to the possibility that democratic openness might allow the Soviets to gain a foothold on the continent. Because of a “growing awareness of Soviet Russia’s aggressive policy,” wrote the State Department’s Division of the American Republics, the United States now “swung back toward a policy of general cooperation [with dictators] that gives only secondary importance to the degree of democracy manifested by [Latin America’s] respective governments.”<sup><a href="#footnote10">10</a></sup> Another reason was to protect investment, as democracy led to a wave of strikes calling for more humane standards of living, better wages, and land and labor reform. Threatened by escalating labor unrest, U.S. corporations demanded protection from Washington and stepped up their patronage of local conservative movements.<sup><a href="#footnote11">11</a></sup>
  <br /><br />
  Moreover, by the early 1950s, Washington found that it was increasingly difficult merely to support dictators from the sidelines. The frustration of postwar democracy and increased political repression helped radicalize a generation of young nationalists in Latin American states, who began to identify the U.S. not as a model but as an obstacle to reform. In the face of such growing opposition to its hemispheric authority, the U.S. began to take the lead in efforts to “arrest the development of irresponsibility and extreme nationalism,” as Thomas Mann, President Eisenhower’s assistant secretary of state for inter-American affairs, wrote in 1952.<sup><a href="#footnote12">12</a></sup>
  <br /><br />
  President John F. Kennedy went on to establish the Alliance for Progress in 1961, which sought to institute democracy and development in the region in response to the perceived threat of Cuban- and Soviet-backed socialism. This policy waned under the Nixon administration but was reemphasized after the Vietnam War by Congress and President Carter, who both sought to advance human rights in Latin America through means other than intervention. As we shall see, while President Reagan ostensibly espoused similar goals, his tactics differed from President Carter’s.</p>
  <br /><br />
<p><strong>Anastasio Somoza Debayle and the Revolution</strong>
  <br /><br />
  In 1967, Anastasio Somoza Debayle, the son of Somoza García, became president. He was widely disliked in Nicaragua, as he suppressed oppositional elements and enriched himself while in power. In 1972, an earthquake rocked Managua, Nicaragua’s capital, and Somoza exercised “emergency powers” to deal with the earthquake while he and his colleagues stole a majority of international aid sent to Nicaragua in the earthquake’s wake. In 1974, the socialist <a href="n-sandinistas.php" class="content_link">Sandinista National Liberation Front</a> (FSLN a.k.a the Sandinistas) staged a kidnapping of Nicaraguan elites at a Christmas party. In response, Somoza declared a state of siege and engaged in a brutal crackdown marked by serious human rights violations against guerrillas and peasants.  In the United States, where Somoza Debayle had largely been ignored, politicians sought to induce reform in Nicaragua because of its poor human rights record, a trend that continued with the election of President Jimmy Carter in 1977.
  <br /><br />
  Nicaraguan businessmen sought reforms as well, as the regime’s policies were inconsistent with private-sector interests. In 1974, Pedro Joaquín Chamorro, a popular Nicaraguan politician, founded the Union for Democratic Liberation (UDEL), an opposition party supported by Alfonso Robelo (a cottonseed oil manufacturer) and Adolfo Calero (a Conservative politician and manager of a bottling factory). The Sandinistas, too, continued to oppose the regime, beginning with more attacks in 1977. In January 1978, Chamorro was assassinated, which led to widespread protests against the regime despite the fact that the assassins were never conclusively identified. The Sandinistas continued to fight the Somoza regime, and with support from Costa Rica, Venezuela, Panama, and Cuba, they were increasingly successful. By summer 1979, the United States decided that Somoza’s rule was no longer tenable in Nicaragua and, along with other Latin American leaders, sought to moderate the new Nicaraguan government that would inevitably come to power. The Sandinistas paid lip service to this request. On July 19, 1979, the Sandinistas seized power in Nicaragua.</p>
  <br /><br />
<p><strong>Post-Revolution Developments </strong>
  <br /><br />
  After the Sandinistas took power in 1979, they imposed a state of emergency and nationalized various sectors of the economy, expropriated land and businesses from those with ties to the old regime, and reorganized Nicaraguan political life. In an attempt to prevent the Sandinistas from forming ties with the Soviet Union and Cuba, the Carter administration sent aid to the new regime. The Sandinistas nevertheless allied themselves with the Cubans and Soviets; in fact, Cuban military officials advised the Sandinistas after the revolution, and the Sandinistas signed agreements with Moscow in March of 1980. Notably, however, these agreements did not signify or authorize Soviet expansion within the country. The Sandinistas were different from other leftist groups, as it was a coalition of progressive capitalists, socialists, Marxists, and Catholics.
  <br /><br />
  Its leaders were pragmatic, fully aware of the realities of hemispheric power, but also adamant nationalists who took seriously the principle of sovereignty, having observed Nicaragua’s past dealings with the United States. They stood their ground, unwilling to forsake Cuba’s friendship or reject its aid. While they had no desire to replicate Castro’s uncompromising economy or polity, they were dedicated to making Nicaragua more humane through the creation of a mixed economy in which the state directed capital investment and redistributed wealth by providing health care and education. The more Washington attempted to reshape their newly-established government, the more they moved to consolidate their power. The Sandinista’s resolve was taken by those in the U.S. foreign policy establishment as evidence of their totalitarianism – even though throughout the worst of the Contra war, the Sandinistas never violated civil rights or engaged in repression anywhere near to the degree that Somoza had before them.<sup><a href="#footnote13">13</a></sup>
  <br /><br />
  Carter continued to give aid to Nicaragua even as it was discovered that the Sandinistas were sending weapons to Salvadoran rebels. After failed appeals by the Carter and Reagan administrations to the Sandinistas to cease arms trafficking, Reagan ended all aid to Nicaragua. With the Sandinistas still sending arms to El Salvador, Reagan issued an intelligence finding authorizing the CIA to engage in covert action by funding the Contras, ostensibly to support the interdiction of arms going to El Salvador. However, the goal of covert action arguably expanded to include the overthrow of the Sandinistas. It is this framework that eventually led to the “Contra” half of the Iran-Contra affair.</p>
<p><strong>Contras</strong>
  <br /><br />
  Since the start of the Cold War, there was a camp of conservative thinkers within the U.S. foreign policy establishment who rejected the policy of “containment,” arguing instead that Washington should take forceful action to “roll back” Communism.<sup><a href="#footnote14">14</a></sup> The 1979 Nicaraguan revolution proved to be tailor-made for those who wanted to transform America’s foreign policy from containment to rollback. For over a year prior to the 1980 presidential elections, defense activists gathering around Reagan’s candidacy used the Nicaraguan revolution to attack Carter, criticizing his human rights policy and citing his tolerance for “ideological pluralism” as leading to the downfall of Somoza, who for decades served the U.S. as a loyal backstop against Communism.<sup><a href="#footnote15">15</a></sup>
  <br /><br />
  The fall of Somoza and the Sandinista’s unwillingness to cooperate with the United States is what moved those involved within U.S. national security agencies to assemble the remnants of Somoza’s National Guard into a counterrevolutionary force months before Reagan won the presidency – before, even, he had captured his party’s nomination in mid-1980.<sup><a href="#footnote16">16</a></sup>
  <br /><br />
  Just after Reagan’s election, a meeting was brokered between would-be Contra leaders and representatives of the Argentine military junta—which at the time was engaged in a campaign to “disappear” their opposition. This collaboration marked the expansion of Operation Charly, which was the Central American equivalent to Operation Condor enacted in South America from 1968 to 1989. In agreeing to fund and train Contras, Argentina acted not only out of ideological sympathy with the counterrevolutionaries but in hopes of improving diplomatic relations with the United States, which had grown strained under Carter.<sup><a href="#footnote17">17</a></sup> Between 1982, when Argentina’s Falklands War took them out of Central America and left the CIA as the principal sponsor of the Contras, and 1986, when the Iran-Contra Affair exploded in the press, William Casey, head of CIA, and Oliver North, National Security Council staff, presided over the construction of an elaborate transnational support network designed to bypass congressional and public scrutiny.<sup><a href="#footnote18">18</a></sup>
  <br /><br />
  Applying the same logic used to fund and support El Salvador’s counterinsurgency, the Nicaraguan counterrevolution was aimed not at establishing ideological legitimacy for the Contras or winning the allegiance of the majority of the population, but simply making it too painful for the Sandinistas to govern. Many Contras were peasants and farmers who objected to Sandinista land policies and took up arms as a result. Members of the elite and business owners opposed their economic policies and repressive measures and fought the regime, as well. Most notably, José Francisco Cardenal, the former president of the Chamber of Construction, and Enrique Bermúdez, a former colonel in the National Guard, founded the Nicaraguan Democratic Revolutionary Alliance, which later came to be called the Nicaraguan Democratic Force (FDN).
  <br /><br />
  The FDN was the major group of Contras supported by the Reagan administration. Hoping to show a wavering rural population that the Sandinistas could not establish effective sovereignty, the Contras razed cooperatives, schools, health clinics, and power stations and tortured, raped, and murdered civilians, including foreigners who were helping to rebuild Nicaragua. It was also hoped that the Contras would, at the very least, force the Sandinistas to devote scarce resources to the conflict and to impose draconian measures that would eat away at their legitimacy and, with luck, provoke them into attacking Honduras, which would then justify a U.S. response.<sup><a href="#footnote19">19</a></sup>
  <br /><br />
  Soon after the Sandinistas seized power, some segments of Nicaraguan society felt disenchanted with the new regime’s policies and sought to bring about change through armed rebellion.  These counterrevolutionaries, encouraged by the United States, came to be called the “Contras.”</p>
  <br /><br />
<div align=center class="top_link"><p>[ <a href="#headertop">Return to top ]</a></p></div>
<p><!-- Footnotes -->
  <sup><p id="section1">1</p></sup>Greg Grandin, Empire’s Workshop (New York: Henry Holt and Company, LLC, 2006), 31.
  <sup><p id="section2">2</p></sup>For policy intellectuals’ criticism of U.S. actions in Latin America in the second half of the Hoover administration, see the essays under the heading “Our Future Relations with Latin America,” Annals of the American Academy of Political and Social Science 156 (July 1931): 110-36.
  <sup><p id="section3">3</p></sup>Grandin, Empire’s Workshop, 33.
  <sup><p id="section4">4</p></sup>CQ Press, “Inter-American System,” SAGE Publishing. (http://library.cqpress.com/cqresearcher/document.php?id=cqresrre1960021000)
  <sup><p id="section5">5</p></sup>Peter Gowan, The Global Gamble: Washington’s Faustian Bid for World Dominance, London: Verso, 1999.
  <sup><p id="section6">6</p></sup>Grandin, Empire’s Workshop, 39-40.
  <sup><p id="section7">7</p></sup>Leslie Bethel and Ian Roxboroug, eds., Latin America between the Second World War and the Cold War, 1944-1988, Cambridge: Cambridge University Press, 1992.
  <sup><p id="section8">8</p></sup>David Schmitz, Thank God They’re On Our Side: The United States and Right Wing Dictatorships, 1921-1965, Chapel Hill: University of North Carolina Press, 1999, pp. 140-57.
  <sup><p id="section9">9</p></sup>Grandin, Empire’s Workshop, 40-41.
  <sup><p id="section10">10</p></sup>David Schmitz, Thank God They’re On Our Side: The United States and Right Wing Dictatorships, 1921-1965, p. 145.
  <sup><p id="section11">11</p></sup>Grandin, Empire’s Workshop, 41.
  <sup><p id="section12">12</p></sup>Walter LaFeber. “Thomas C. Mann and the Devolution of Latin American Policy: From the Good Neighbor to Military Intervention,” Behind the Throne, ed. McCormick and LaFeber, p. 174.
  <sup><p id="section13">13</p></sup>Grandin, Empire’s Workshop, 112.
  <sup><p id="section14">14</p></sup>Grandin, Empire’s Workshop, 110.
  <sup><p id="section15">15</p></sup>Grandin, Empire’s Workshop, 112.
  <sup><p id="section16">16</p></sup>Grandin, Empire’s Workshop, 113.
  <sup><p id="section17">17</p></sup>Ibid.
  <sup><p id="section18">18</p></sup>Grandin, Empire’s Workshop, 115.
  <sup><p id="section19">19</p></sup>Kornbluh, “Nicaragua: U.S. Proinsurgency Warfare against the Sandinistas,” Low-Intensity Warfare, ed. Klare and Kornbluh, p. 140;</p>
<div><br /><br /><br />
</div>
</div>

<? require ('templates/footer.php'); ?>
