<? require ('templates/header.php'); ?>
<title>Understanding the Iran-Contra Affairs - The Iran-Contra Affairs</title>
</head>
<? require ('templates/irancontrabanner.php'); ?>

<div style="margin: 10px 0px 0px 20px; width: 760px" align="justify" id="welcomenote">
<div align="left" class="bread_crumbs"><a href="index.php">Home</a> &raquo;  <a href="iran-contra-affairs.php">The Iran Contra Affairs</a> &raquo;  Nicaragua: The Contras</div>
  <h2><a name="headertop" id="headertop"></a><br />The Counterrevolutionaries ("The Contras")</h2>
<div style="margin: 0px 0px 0px 20px">
  <p><strong>Beginnings</strong>
    <br /><br />
    Within a year of the Sandinistas’ capture of power, those opposed to the regime began to engage in violent actions. Crude organizations of fighters were seeking to start a counterrevolution.  These disparate groups comprised former National Guardsmen, ex-Sandinista soldiers critical of the new regime, and peasants and farmers upset with “intrusive” Sandinista land policies.  Nicaraguan exiles, including former guardsmen and members of the Conservative Party, gathered in El Salvador, Honduras, Guatemala, and Miami and discussed the prospect of both unarmed and armed opposition to the Sandinistas. Many exiles came to see armed resistance as the only feasible means to moderate Nicaragua; two of them, José Francisco Cardenal (a former president of the Chamber of Construction) and Enrique Bermúdez (a former colonel in the National Guard) formed a “political-military alliance” that would come to be called the Nicaraguan Democratic Force (FDN), the main Contras faction.
    <br /><br />
    By 1980, Nicaraguan exiles were being trained at camps run by Cuban exiles in Florida (in 1960, the U.S. had used Nicaragua as a staging area for the unsuccessful Bay of Pigs invasion). Although the Contras’ camps received increasing attention in the press in 1981 and the Nicaraguans spoke openly of their goal of overthrowing the Sandinistas, no action was ever taken by the U.S. Department of Justice to enforce the Neutrality Act, which prevented the U.S. from involving itself in a foreign war. In December 1981, President Ronald Reagan signed a secret directive authorizing an expenditure of $19 million to conduct paramilitary operations in Nicaragua. Administration officials claimed before Congressional intelligence committees that the purpose of aid to the Contras was interdicting arms allegedly being supplied to the Salvadoran revolutionaries by the Nicaraguan government. Despite this claim, David MacMichael, a CIA intelligence analyst from 1981 to 1983, charged in June 1984 that the CIA had “systematically misrepresented” Nicaraguan aid to the Salvadoran rebels. Since April 1981, he said, there had been no verified reports of arms shipments from Nicaragua to El Salvador.<sup><a href="#footnote1">1</a></sup></p>
  <p><strong>Composition</strong>
    <br /><br />
    The soldiers under the contra leadership consisted of former National Guard enlistees, many of whom had fled to Honduras after the revolution and who sought revenge; former Sandinista fighters who felt betrayed; some Protestant evangelicals and Catholics who were angered by Sandinista opposition to their religion; farmers who were disaffected by the revolution; and Nicaraguan Miskito Indians and Creoles who opposed the regime. According to Kagan, when the Americans began their covert support of the Contras, there were fewer than 2,000 anti-Sandinista fighters, only a few hundred of which were members of the FDN. By the end of 1983, however, there were up to 6,000 fighting Contras. The Contras further gained support among populations who were disaffected by Sandinista economic policies.</p>
  <p><strong>Early Foreign Support</strong>
    <br /><br />
    The Argentinean government had begun supporting Bermúdez and his military forces (the Fifteenth of September Legion) even before the founding of the FDN. The Argentineans gave money and advisers to Bermúdez’s forces in Honduras and also provided training. The Honduran military also provided support and shelter to the Contras. This support continued throughout much of the counterrevolution due to U.S. financial and military assistance to Honduras.
    <br /><br />
    In late 1981, the Reagan Administration settled on a policy of providing arms, money, and equipment to the Argentinean-backed Contras. This followed President Carter’s authorization, in early 1980, of CIA financial support to the Nicaraguan opposition (for the purposes of “organization and propaganda,” but not “armed actions”) and President Reagan’s March 1981 authorization of CIA covert action to interdict arms trafficking to El Salvador (which allowed the CIA to meet with Nicaraguan rebel leaders and their Honduran supporters, but which did not allow the CIA to arm rebel groups). U.S. covert support for and involvement in the Contras’ operations would eventually culminate in the Iran-Contra Affair; more specific information on operational support can be found here<a href="n-contrasus.php" class="content_link">here</a>.</p>
  <p><strong>Leadership and Organization</strong>
    <br /><br />
    The main contra force, the FDN, grew out of the Fifteenth of September Legion, which was established by Somoza’s National Guardsmen who had fled into neighboring Honduras, El Salvador, and Guatemala as the Sandinistas took power in July 1979. A July 1982 Defense Intelligence Agency Weekly Summary described the Legion as a “terrorist group.” Some 50,000 Nicaraguans had died in the revolution to rout the National Guard and overthrow the 44-year Somoza family dictatorship. National Guardsmen were responsible for the rape, torture, and wounding of thousands of other Nicaraguan women, men, and children.<sup><a href="#footnote2">2</a></sup>
    <br /><br />
    Once the United States became involved with maintaining the Contras, it sought to unite the anti-Sandinista forces (the FDN and others) and create an “attractive” political identity to attract support at home and abroad. In testimony before Congress in January 1985, then Assistant Secretary of State for International Affairs Langhorne Motley, claimed:
    <br/><br />
      <p style="margin-left: 40px">The [Contras] freedom fighters are peasants, farmers, shopkeepers, and vendors. Their leaders are without exception men who opposed Somoza.</p>
    <br /><br />
    As mentioned, former Somoza National Guard officers dominated the military hierarchy of the FDN. In a staff report, the Congressional Arms Control and Foreign Policy Caucus found that 46 of the 48 positions in the FDN’s military command structure were held by former guardsmen.<sup><a href="#footnote3">3</a></sup> To counter this, the CIA created a new six-member “political directorate,” unveiled at a December 1982 press conference in Miami. Edgar Chamorro, chief public spokesman for the Contras’ directorate until December 1984, recalls that the directorate was established “in a great hurry… in a week. We complained about his. They were just improvising, reacting to things. They said… they had to repackage the program in a way to be palatable to Congress.”<sup><a href="#footnote4">4</a></sup> The day before the press conference, the CIA held a briefing and rehearsal. Chamorro recalls:
    <br /><br />
      <p style="margin-left: 40px">[CIA Agent Tony] Feldman introduced two lawyers from Washington who briefed us on the Neutrality Act, the American law prohibiting private citizens from waging war on another country from U.S. territory. Feldman was worried we were going to tell the press that we were trying to overthrow the Sandinistas, which, of course, is exactly what we wanted to do. He emphasized that we should say instead that we were trying to “create conditions for democracy.”
      <br /><br />
      After the briefing we asked each other the questions we were likely to face in the morning… “Have you had any contact with U.S. government officials?” The CIA men agreed there was no way to finesse this one. We simply had to lie and say, “No.”<sup><a href="#footnote5">5</a></sup></p>
    <br /><br />
    Chamorro was ousted by the FDN because of his candor about the Contras’ standard practice of killing Sandinista prisoners and collaborators – later he would write, “It was like stomping on a cockroach to them,” – his criticism of the CIA terror manual, and his outspoken assertion that, “The Americans built up the Contras to stop the flow of weapons from Nicaragua to El Salvador. Privately they promised us on many different occasions that they were helping us overthrow the Nicaraguan government.”<sup><a href="#footnote6">6</a></sup> After a March 1982 attack by anti-Sandinista forces prompted more radical measures taken by the Sandinistas, Alfonso Robelo, a former member of the post-revolution Nicaraguan government, and Edén Pastora, who led anti-Somoza troops during the revolution, expressed their support for armed resistance against the Sandinistas. Pastora formed an armed anti-Sandinista resistance group in Costa Rica called the Democratic Revolutionary Alliance (ARDE). Arturo Cruz, also a member of the Nicaraguan government, resigned in protest of what he saw as an increasingly radical regime and supported armed revolution. In June 1985, after U.S. efforts to unite these opposition leaders, Cruz, Robelo, and Calero formed the United Nicaraguan Opposition (UNO), which theoretically subsumed the FDN.</p>
    <br /><br />
  <p><strong>Criticism over Human Rights and U.S. Intervention</strong>
    <br /><br />
    The Contras are frequently criticized for their alleged human rights abuses. In July 1985 Americas Watch, a Human Rights Watch organ founded in 1981 while wars engulfed Central America, released a report titled <i>Human Rights in Nicaragua: Reagan, Rhetoric and Reality</i>. In it, the committee finds the Reagan administration’s approach to Nicaraguan human rights to be “deceptive and harmful.” The report states:
    <br /><br />
      <p style="margin-left: 40px">The Administration’s accusations against Nicaragua rest upon a core of fact; the Sandinistas have committed serious abuses, especially in 1981 and 1982, including arbitrary arrests and the summary relocation of thousands of Miskito Indians. Around the core of fact, however, U.S. officials have built an edifice of innuendo and exaggeration. The misuse of human rights data has become pervasive… When inconvenient, findings of the U.S. Embassy in Managua have been ignored; the same is true of data gathered by independent sources. In Nicaragua, there is no systematic practice of forced disappearances, extrajudicial killings or torture – as has been the case with the “friendly” [counterrevolutionary] armed forces of El Salvador. While prior censorship has been imposed by emergency legislation, debate on major social and political questions is robust, outspoken, even often strident. …Nor has the Government practiced elimination of cultural or ethnic groups, as the [Reagan a]dministration frequently claims; indeed in this respect, as in most others, Nicaragua’s record is by no means so bad as that [of] Guatemala, whose government the [a]dministration consistently defends. Moreover, some notable reductions in abuses have occurred in Nicaragua since 1982, despite the pressure caused by escalating external attacks… [The] description of a totalitarian state bears no resemblance to Nicaragua in 1985.<sup><a href="#footnote7">7</a></sup></p>
    <br /><br />
    Reed Brody, a U.S. lawyer who was engaged in a fact-finding mission in Nicaragua from September 1984 to January 1985 to investigate alleged Contras human rights incidents released a report, <i>Contra Terror in Nicaragua</i>, which came to be known as the “Brody Report.” The Report provided the general public with detailed accounts of human rights abuses through eyewitness statements. On March 7, 1985, <i>The New York Times</i> ran a front-page story reporting on four incidents chosen at random from Brody's assessment. Americas Watch spot-checked Brody’s findings, confirming them as background to their March 1985 report <i>Violations of the Laws of War by Both Sides in Nicaragua</i>, which found that:
      <p style="margin-left: 40px">Contra forces have systematically violated the applicable laws of war throughout the conflict. They have attacked civilians indiscriminately; they have tortured and mutilated prisoners; they have murdered those placed <i>hors de combat</i> [out of action due to injury] by their wounds; they have taken hostages; and they have committed outrages against personal dignity.</p>
    <br /><br />
    The Americas Watch report found that on the Nicaraguan government side there had also been abuses, but there was a sharp decline in violations of the laws following 1982. A senior State Department official responded to the Americas Watch charges about the contras by saying, “It seems to be what you would expect to have in a war.” Another administration official commented, “What we see is that the Sandinista casualties are usually legitimate battle victims,” adding, “The Contras have a tendency to kidnap young girls.”<sup><a href="#footnote8">8</a></sup> In an April follow-up report, Americas Watch reconfirmed its earlier findings and concluded that, “the [C]ontras – particularly the largest of the contras forces, the Fuerza Democratica Nicaraguense (FDN) – practice terror as a deliberate policy.”<sup><a href="#footnote9">9</a></sup>
    <br /><br />
    In their talks with State Department officials, staffers from the Washington Office on Latin America (WOLA) – a private church-supported, human rights organization – were told that these officials were not appraised of the validity of Reed Brody’s allegations about contra atrocities because they did not know what was going on in the field. U.S. intelligence had not been “tasked” to report on this. A high-ranking State Department official described the situation as “intentional ignorance.”<sup><a href="#footnote10">10</a></sup>
    <br /><br />
    On May 10, 1984, the International Court of Justice (World Court) ruled unanimously that the U.S. should immediately halt any attempts to mine or blockade Nicaraguan ports, and 14 to one that Nicaragua’s political independence “…should be fully respected and should not be jeopardized by any military or paramilitary activities.” The Court included judges from U.S. allies, such as Great Britain, France, Italy, Japan, and West Germany. The Reagan administration declared it would not accept World Court decisions regarding Central America for two years.<sup><a href="#footnote11">11</a></sup></p>
    <br /><br />
  <p><!-- Footnotes -->
    <sup><p id="section1">1</p></sup>“Ex-CIA Analyst Disputes U.S. Aides on Nicaragua,” Washington Post, June 13, 1984 and “In From the Cold and Hot for the Truth,: New York Times, June 11, 1984.
    <sup><p id="section2">2</p></sup>Reed Brody, Contra Terror in Nicaragua, Report of a Fact-finding Mission: September 1984-January 1985 (South End Press Collective, 1985), 10.
    <sup><p id="section3">3</p></sup>Brody, “Contra Terror,” 3.
    <sup><p id="section4">4</p></sup>Brody, “Contra Terror,” 13.
    <sup><p id="section5">5</p></sup>Edgar Chamoiro with Jefferson Morley,  “Confessions of a ‘Contra,’” New Republic August 5, 1985.
    <sup><p id="section6">6</p></sup>Brody, “Contra Terror,” 15.
    <sup><p id="section7">7</p></sup>Brody, “Contra Terror,” 4-5.
    <sup><p id="section8">8</p></sup>Brody, “Contra Terror,”, 6-7.
    <sup><p id="section9">9</p></sup>Brody, “Contra Terror,” 6-7.
    <sup><p id="section10">10</p></sup>Brody, “Contra Terror,” 7-8.
    <sup><p id="section11">11</p></sup>Brody, “Contra Terror,” 12.</p>
<div align=center class="top_link"><p><a href="#headertop">[ Return to top ]</a></p></div>
<div><br /><br /><br />
</div>
</div>

<? require ('templates/footer.php'); ?>
