<? require ('templates/header.php'); ?>
<title>Understanding the Iran-Contra Affairs - The Iran-Contra Affairs</title>
</head>
<? require ('templates/irancontrabanner.php'); ?>
    
<div style="margin: 10px 0px 0px 20px; width:760px" align="justify" id="welcomenote">
<div align="left" class="bread_crumbs"><a href="index.php">Home</a> &raquo;  <a href="iran-contra-affairs.php">The Iran Contra Affairs</a> &raquo;  Nicaragua: U.S. Support for the Contras</div>
<h2><a name="headertop" id="headertop"></a><br /> The Counterrevolutionaries (The Contras)</h2>
<h3>U.S. Support for the Contras</h3>
<div style="margin: 0px 0px 0px 20px">
  <p><strong>U.S. Aims </strong><br />
    <br />
    The United States provided money, material, and operational support to the contras.&nbsp; However, the purpose of the United States’ Nicaragua policy during the early years of the Reagan Administration is a matter of debate.&nbsp; According to Kagan, the ostensible goal of U.S. support for the contras, according to some in the Administration, was not to overthrow the Sandinistas but to compel them to stop sending arms to the Salvadoran rebels.&nbsp; This changed, however, with the formulation of the Reagan Doctrine in 1982, which was “a policy of supporting democratic reform or revolution everywhere.”&nbsp; At this point, the goal of the Reagan Administration’s policy in Nicaragua arguably became to overthrow the Sandinistas.&nbsp; Others, such as Draper, suggest that regime change was the goal of the Administration’s Nicaragua policy from the beginning.&nbsp; </p>
  <p><strong>U.S. Actions in Nicaragua, August 1981 to December 1982</strong><br />
    <br />
   In August 1981, a CIA official met with Honduran military officials, Argentine advisers, and the FDN leadership and expressed his support for the contra operations.&nbsp; On November 1, the Director of the CIA William Casey met with the Chief of Staff of the Argentine military; the two purportedly agreed that Argentina would oversee the contras and the United States would provide money and weapons.&nbsp; In late 1981, President Reagan authorized the U.S. to support the contras by giving them “money, arms, and equipment” through Argentina, with the potential for “the occasional direct involvement of the United States in supporting individual operations.”&nbsp; As a result, according to Kornbluh, “the frequency and destructiveness of the contra attack[s] increased rapidly.”&nbsp; So, too, did their numbers.&nbsp; Toward the end of 1982, the contras (who operated out of Honduras) were conducting attacks deep inside Nicaragua.</p>
  <p><strong>The First Boland Amendment</strong><br />
    <br />
  As contra attacks continued throughout 1982, the U.S. press began to report on U.S. support for the rebels.&nbsp; Liberal members of Congress condemned the policy, arguing that it was immoral and perhaps illegal.&nbsp; Eventually, Congressman Edward Boland (D-MA), Chairman of the House intelligence committee, offered an amendment “prohibiting the use of funds 'for the purpose of’ overthrowing the government of Nicaragua or provoking a war between Nicaragua and Honduras” which became law on December 21, 1982.&nbsp; The use of funds for this purpose had actually been secretly prohibited per an agreement between Congress and the White House; thus, the amendment had no practical effect on the conduct of U.S. policy.&nbsp; Kagan identifies a “loophole” in the law; namely, that as long as the United States itself did not intend to overthrow the Nicaraguan government, the United States could support the contras, who did have that intent.&nbsp; Indeed, according to a PBS <em>Frontline</em> documentary, the amendment did not affect the conduct of the war in Nicaragua.</p>
  <p><strong>U.S. Policy between Boland I and Boland II</strong><br />
    <br />
    After Boland I, contra attacks in Nicaragua continued to grow.&nbsp; Despite summary executions of Sandinista soldiers and other brutal measures, the contras often found support among the people in the countryside.&nbsp; The number of contra soldiers continued to grow as well.&nbsp; To counter this threat, the Sandinistas received operational support from a Cuban military general and weapons from the Soviet Union.&nbsp; The CIA began airlifting supplies to the contras, and the contras conducted “spectacular” guerilla assaults on their targets.&nbsp; During the second half of 1983, with the help of the CIA, the contras conducted air strikes on Sandino airport near Managua and other targets.&nbsp; The CIA itself used its own assets to carry out some covert actions in Nicaragua, including destroying several fuel tanks.&nbsp; The CIA also placed mines in Nicaraguan harbors on January 7, 1984 and February 29, 1984, damaging several ships.&nbsp; The contras initially took credit for the mining, but the <em>Wall Street Journal</em> reported it to be the work of the CIA a few months later.&nbsp; Moreover, it was discovered that Lieutenant Colonel Oliver North, a U.S. Marine who worked on the National Security Council staff at the Reagan White House, had known of and recommended the operation.</p>
  <p><strong>The Second Boland Amendment</strong><br />
    <br />
  As the war in Nicaragua grew, many Congresspersons were concerned that the Administration’s policies violated the Boland Amendment, prompting political wrangling involving the White House and Congress over contra funding.&nbsp; The revelation that the CIA was responsible for mining Nicaragua’s harbors infuriated Congresspersons of both political parties, including Senator Barry Goldwater (R-AZ), chairman of the Senate intelligence committee, who felt that the CIA had failed to inform the committee of the operation in advance as required by law.&nbsp; (In fact, DCI Casey may have informed the committee, albeit in an arguably veiled way.)&nbsp; As a result, the second Boland Amendment was passed on October 12, 1984.&nbsp; It read: <br />
    No appropriations or funds made available pursuant to this [authorization bill] to the Central Intelligence Agency, the Department of Defense, or any other agency or entity of the United States involved in intelligence activities may be obligated or expended for the purpose or which would have the effect of supporting, directly or indirectly, military or paramilitary operations in Nicaragua by any nation, group, organization, movement, or individual.<br />
    For all intents and purposes, this amendment appeared to prohibit the funding of the contras with U.S. government funds. </p>
  <p><strong>U.S. Policy Framework Post-Boland</strong><br />
    <br />
    The second Boland Amendment certainly forced the Administration to change some of its policies even as it was trying to get the amendment repealed.&nbsp; Draper identifies two ways in which the Administration tried to get around Boland.&nbsp; The first was by getting private American citizens and third-party countries to donate money to the contras since Boland did not explicitly outlaw these parties from funding the Contras.&nbsp; The second was by controlling U.S. contra policy and support from within the National Security Council (NSC), which is “the President's principal forum for considering national security and foreign policy matters with his senior national security advisors and cabinet officials.”&nbsp; This option was based on the fact that the NSC was not explicitly mentioned in Boland and that, since the NSC deals with policymaking, it is arguably not an “intelligence agency or entity” involved in “intelligence activities.”</p>
  <p><strong>Funding </strong></p>
  <div style="margin: 0px 20px 0px 20px"><em>Third-Country Funding</em><br />
    <br />
    Obtaining funds for U.S. foreign policy goals from third-party had been considered by 1983.&nbsp; That spring, Robert McFarlane, before he became President Reagan’s National Security Adviser, suggested that Israel could give some of the foreign aid it received from the United States to U.S. allies in Central America.&nbsp; Later that year, Secretary of State George Shultz suggested that “alternative benefactors” should be found to fund the contras.&nbsp; <br />
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br />
    After the passage of the second Boland Amendment, the Administration again considered this plan.&nbsp; In March and April, McFarlane, with the support of DCI Casey, tried to get the Israelis to fund the Contras, but they refused.&nbsp; Secretary Shultz now objected to this option, stating that it might be illegal for the United States to get other countries, especially recipients of U.S. aid, to fund the contras.&nbsp; Nevertheless, McFarlane, North, and others sought funds from other countries for the contras.&nbsp; McFarlane was able to get a total of $32 million from Saudi Arabia between 1984 and 1986; McFarlane maintained that he did not solicit the money but merely expressed that that funds for the contras would be appreciated.&nbsp; Later, North was able to secure two $1 million contributions to the contras from Taiwan.<br />
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br />
    At the end of 1985 and as part of the Intelligence Authorization Act, Congress outlawed most U.S. government agencies from soliciting money from third-party countries to fund the contras.&nbsp; However, the amendment allowed the State Department to solicit such funds for “humanitarian assistance only,” provided that the money donated was from the countries’ own funds and that the U.S. did not enter into “any express or implied arrangement making U.S. provision of assistance to the third country contingent on the third country’s assistance to the contras.”&nbsp; North, Assistant Secretary of State Elliot Abrams, National Security Adviser John Poindexter, and others had the idea of getting $10 million from the Sultan of Brunei for the contras, but the money was deposited in the wrong bank account.</p>
    <p><em>Private Funds</em><br />
      <br />
      DCI Casey was allegedly the first to suggest the solicitation of private funds for the contras, but the CIA did not coordinate these activities.&nbsp; Some in the administration had the idea to set up a tax-exempt foundation to collect money for the contras, but the individual who eventually carried out this plan was Carl R. Channell, a conservative political consultant and lobbyist.&nbsp; In early 1985, Channell met the public relations representative of the Nicaraguan Refugee Fund.&nbsp; Channell soon found himself and Daniel Conrad, another political fundraiser, hosting a fundraising dinner for the NRF.&nbsp; Channell continued fundraising, and he was eventually introduced to Oliver North.&nbsp; North began briefing dinner guests at Channell’s fundraisers so that they would contribute to the contra cause.&nbsp; With the help of others, Channell organized fundraisers that also featured other Administration officials, including the president, and he even arranged for a meeting between a potential donor and Adolfo Calero. &nbsp; In 1985 and 1986, Channell raised over $12 million, of which $2.7 million went to the contras.&nbsp; Draper notes that North had a very important role in this operation and that Reagan himself knew about it.</p></div>
  <strong>Operation Support</strong><br />
<br />
<div style="margin: 0px 20px 0px 20px"><em>Arms Deals</em><br />
  <br />
  In addition to seeking alternative funding, North and others sought to provide the contras with arms and supplies.&nbsp; For this, North worked with Richard Secord and Albert Hakim.&nbsp; (Some weapons were obtained with North’s knowledge by John Singlaub, a retired U.S. Army general who also assisted in securing the money from Taiwan and who, with the support of Sen. Jesse Helms and Abrams, attempted to unite the contras in the north and south.)&nbsp; Secord was a retired Air Force General who had been implicated in a scandal in which an ex-CIA agent sold arms to Libya and who had met North in 1981 regarding an unrelated matter.&nbsp; Hakim was an Iranian businessman who met Secord while the latter was stationed in Iran.&nbsp; Following Secord’s retirement in 1983, the two began to do business with one another.&nbsp; DCI Casey recommended Secord to North as someone who could be involved in helping the contras.&nbsp; North solicited Secord’s help in summer 1984, and Secord and Hakim agreed to participate.&nbsp; North introduced the two to Calero, and in November 1984, the three solidified their first agreement in which Secord and Hakim would obtain arms for the contras.&nbsp; By the next summer, the contras got their arms solely from Secord and Hakim, who eventually sold a total of $11 million in arms to the contras.</p>
  <p><em>Air Supply Ops</em><br />
    <br />
    The second Boland Amendment prohibited the CIA from providing the operational support to the contras that it once had.&nbsp; In order to get around this restriction, North and others set up a “miniature CIA,” in Draper’s words, to deliver arms to the contras.&nbsp; In July 1985, North asked Secord “to build and oversee an air resupply operation for the contras.”&nbsp; Much of the money raised for the contras from private citizens and other countries went to this operation, and an airstrip was constructed in Costa Rica for the operation’s use (however, this was closed at the behest of Costa Rican President Óscar Arias Sánchez in September 1986).&nbsp; However, due to poor equipment and other issues, there were no arms deliveries until April 1, 1986, and the initial drops only supplied contra forces in Honduras.&nbsp; By May, according to Draper, contras in both the north and south were receiving air drops, although Kagan quotes an agent of the supply effort as saying that the operation was not “viable” until mid-September.&nbsp; On October 5, 1986, one of the supply aircraft was shot down by the Sandinistas, and crewmember Eugene Hasenfus was captured.&nbsp; Despite the fact that this event did not cause Congress to immediately conduct in-depth investigation into U.S. involvement in supplying the contras, North and others in the Administration decided to end the operation.</p>
  <p><em>Intelligence Support</em><strong><br />
    </strong><br />
    North also provided “broader strategic military advice.”&nbsp; He provided the contras with U.S. intelligence information on the location of new HIND helicopters the Soviets had shipped to the contras, an act which McFarlane later stated could have violated the Boland Amendment.&nbsp; North also passed along intelligence information from the CIA and DoD to the contras.&nbsp; He attempted to help secure the services of a British mercenary, David Walker, for the contras, but Walker’s operations were never carried out.&nbsp; Furthermore, North tried to get approval for a contra attack on a cargo ship suspected of carrying arms for the Sandinistas, although this operation never occurred.</p>
</div>
<p><strong>Congressional Funding </strong></p>
<p> While North and others were coordinating financial and operational support to the contras more or less out of the public view, the Administration was considering ways to secure Congressional funding for the contras.&nbsp; In addition to Boland, Congress passed a provision in which $14 million in military assistance could later be given to the contras at the behest of both Houses of Congress.&nbsp; This aid was finally released for “humanitarian purposes” in August 1985, and that same year, the Congress “loosened” the Boland Amendment’s restrictions on so that the CIA could “provide training and intelligence information to the contras” as long as it was not for the conduction of or logistics for combat operations.&nbsp; In June 1986, $100 million in aid to the contras was passed by Congress.</p>

<p><strong>The Diversion</strong></p>
<p>While the Administration was discussing contra funding in 1986, “North came upon the idea of overcharging the Iranians” for weapons sold to them by Americans “and using the surplus to fund the contra resupply operation and other covert activities.” Manucher Ghorbanifar apparently suggested this idea to George Cave, a CIA official, in March of that year.&nbsp; In any event, in early April, North wrote a memo to Poindexter and Reagan in which he wrote that $12 million of the profit Secord and Hakim made from the sale of arms to Iran “will be used to purchase critically needed supplies for the Nicaraguan Democratic Resistance Forces;” this became known as the “diversion.”&nbsp; On November 25, 1986, in the midst of growing attention paid to the arms deals to Iran, Attorney General Edwin Meese III announced the diversion.&nbsp; Of all of the events of the Iran-Contra Affairs, this was arguably the most explosive.<br />
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br />
  <strong>Media Discovery and Congress’s Reaction</strong><br />
  <br />
  As early as June 1985, the media began publishing stories about U.S. ties to the contras.&nbsp; North’s name first appeared in a June 24, 1985 article in the <em>Miami Herald</em> in which Edgar Chamorro was interviewed.&nbsp; Other newspapers, including the <em>New York Times</em> and the <em>Washington Post</em> began running with the story as well.&nbsp; As a result, Congress questioned McFarlane and North.&nbsp; The two of them, along with Poindexter, “deceived and obstructed” Congress, according to Draper.&nbsp; Thus, Congress did not conduct any oversight at this point, although the answers the three gave to Congress later formed the basis for their criminal charges.<br />
  <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br />
    </strong>In 1986, the media again brought attention to North’s activities.&nbsp; A Sandinista helicopter was shot down in December 1985, and in January, the <em>Miami Herald</em> reported that the missile used in the attack was obtained by Singlaub.&nbsp; In April, the newspaper again referred to North, stating that he may have broken the prohibition on aid to the contras.&nbsp; The media continued with the story throughout the summer amidst White House denials. &nbsp;Thus, according to Draper, “By mid-1986, U.S. clandestine support for the contras was an open secret.”&nbsp; Congress again sought information on these activities, but Poindexter stonewalled Congress and North was misleading, as he later admitted.&nbsp; Thus, Congress again exercised no real oversight function over the NSC, and further failed to do so when Hasenfus’s aircraft was shot down.&nbsp; It was not until the exposure of the Iran side of things that the Iran-Contra Affairs became a political crisis of such magnitude.</p>
</p>
<p><strong>Impact on the Contras</strong></p>
 The impact of the activities of North and the others is important to consider.&nbsp; Secord and Hakim were interested in profiting off of their activities; thus, the contras did not receive all of the money that North intended they receive.&nbsp; As Kagan writes, “For all the controversy raised about the diversion, the contras were fortunate if they received $2 million worth of tangible benefits [between January and October 1986,] an amount that paled in comparison to the far less controversial $32 million they ultimately received from Saudi Arabia.”&nbsp; The figure of $2 million includes the estimated $600,000 that the contras received as a result of the diversion.&nbsp; Meanwhile, the accounts of Secord and Hakim, when frozen during the Iran-Contra Affairs, still had $8 million.
<div>
  </div>

</div>
<div align=center class="top_link"><p>[ <a href="#headertop">Return to top ]</a></p></div>
<div>
<div><br /><br /><br />
</div>
</div>

<? require ('templates/footer.php'); ?>