<? require ('templates/header.php'); ?>
<title>Understanding the Iran-Contra Affairs - The Iran-Contra Affairs</title>
</head>
<? require ('templates/irancontrabanner.php'); ?>
    
<div style="margin: 10px 0px 0px 20px; width: 760px" align="justify" id="welcomenote">
<div align="left" class="bread_crumbs"><a href="index.php">Home</a> &raquo;  <a href="iran-contra-affairs.php">The Iran Contra Affairs</a> &raquo;  Nicaragua: The Sandinistas</div>
<h2><a name="headertop" id="headertop"></a><br /> 
The Sandinistas</h2>
<h3>Ideology and Domestic Politics</h3>
<div style="margin: 0px 0px 0px 20px">
  <p><strong>Founding</strong><br />
    <br />
    In 1961, the Sandinista National Liberation Front (<em>Frente Sandinista de Liberación Nacional</em>, or Sandinistas) was founded by Silvio Mayorga, Tomás Borge, and Carlos Fonseca.&nbsp; The group took its name from Augusto Cesár Sandino, who led a Liberal peasant army against the government of U.S.-backed Adolfo Díaz and the subsequent Nicaraguan government in the late 1920s and early 1930s.&nbsp; Inspired by Fidel Castro's and Che Guevarra's Cuban Revolution, the group sought to be “a political-military organization whose objective is the seizure of political power through the destruction of the bureaucratic and military apparatus of [Somoza's] dictatorship.”&nbsp; <br />
    <br />
    According to Dennis Gilbert, the first members of the FSLN were nationalistic students who were outraged at conditions in Nicaragua under Somoza.&nbsp; They were also outraged at the United States over what they saw as consistent U.S. intervention in Nicaraguan affairs.&nbsp; He argues that the Sandinistas' ideology was rooted in Marxism and in a mistaken reading of Sandino as a pseudo-Marxist.&nbsp; (Sandino himself was a populist who sought Nicaraguan independence from U.S. imperialism.&nbsp; While he sought relief for the poor, he did not advocate for a Marxist class struggle.)<br />
    </p>
  <p>However, the Sandinistas were heavily influenced by Marixst-Leninist teachings, as the party leaders themselves sometimes admitted, but they interpreted these ideas in the context of their view of Nicaragua's history.&nbsp; Specifically, they thought of themselves as a Leninist vanguard party, a group of “professional revolutionaries” that would unite the Nicaraguan workers and peasants to destroy the “present system of capitalist exploitation and oppression” run by the Somoza dynasty and supported by the United States.&nbsp; After they had rid Nicaragua of those who were resistant to change, the FSLN would lead Nicaragua toward socialism, at least in a broad sense; as Gilbert notes, the Sandinistas did not all agree on what socialism actually meant.    &nbsp;&nbsp;&nbsp;&nbsp; </p>
  <p><strong>Post-revolution politics and ideology</strong><br />
    <br />
    Despite their staunch socialist leanings, the Sandinistas united with other groups in opposition to Somoza in order to “mask” the true nature of their revolution so as to not evoke the ire of the United States.&nbsp; After the broad-based coalition against Somoza triumphed, the FSLN sought to consolidate its power to prevent the bourgeoisie from waging a successful counterrevolution.&nbsp; They organized segments of society, such as peasants and laborers, into “mass organizations” which would ostensibly defend the revolution.&nbsp; The Sandinistas presented these organizations as giving the Nicaraguan people a voice in the new revolutionary government and as promoting democratic participation.&nbsp; The masses also became the physical defenders of the revolution during the contra war, when the government distributed weapons to militias.&nbsp; The FSLN, moreover, instituted a National Literacy Crusade, which, according to Kagan, served both to increase literacy and to ideologically indoctrinate students. <br />
    <br />
  Sandinista economic policies also reflected their socialist ideology.&nbsp; The Sandinistas nationalized Nicaragua's financial sector and major exports.&nbsp; They seized some farm land and encouraged the formation of state farms and farming cooperatives, although they eventually distributed land to individual peasants as contra resistance grew.<br />
  <br />
  Throughout their rule, the Sandinistas arguably became more radicalized, especially in times of crisis.&nbsp; For example, in 1981, the Sandinistas announced new economic policies designed to weaken the private sector, such as the appropriation of “unused” farmland; the confiscation of businesses that ostensibly threatened the revolution; and the confiscation of the finances of those who had been gone from Nicaragua for at least six months.&nbsp; In 1982, after Argentine-trained rebels blew up two bridges, the Sandinistas declared a state of emergency, and, among other things, restricted the Nicaraguan press.<br />
  <em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br />
    </em><strong>“Democracy”</strong><br />
    <br />
  The Sandinistas fashioned themselves as a democratic movement.&nbsp; Instead of defining democracy in terms of elections, the FSLN believed that democracy meant popular support and participation.&nbsp; In fact, early after the revolution, the FSLN declared that the party would make decisions with the informal input of the people so that formal elections were deemphasized.&nbsp; However, in 1984, facing military pressure from the contras and seeking to gain legitimacy abroad, the Sandinistas held elections in which they were largely successful.&nbsp; Whether this was truly a fair election, though, is a matter of debate; Vanden and Prevost argue that it was, whereas Kagan argues that Sandinistas were not willing to make any real changes regardless of the elections.</p></div>

<div align=center class="top_link"><p>[ <a href="#headertop">Return to top ]</a></p></div>
<h3><br />
  Foreign Relations with the Soviet Bloc</h3>
<div style="margin: 0px 0px 0px 20px">
  <p><strong>Pre-Revolution and Cuba</strong><br />
    <br />
  Throughout their rule, the Sandinistas maintained a close relationship with Cuba.&nbsp; Prior to the revolution, the FSLN had been inspired by the socialist revolution in Cuba.&nbsp; During the revolution in Nicaragua, the FSLN received arms from Panama, Cuba, and Venezuela, and logistical support from Costa Rica, although Cuba's Fidel Castro was the only country that wanted to see a socialist revolution in Nicaragua (the other countries supported the FSLN as a viable opponent to Somoza and to prevent the radicalization of the revolution).&nbsp; Immediately after the revolution, in fact, Cuba sent advisors to Nicaragua to consult with the new government about the formation of its policies.&nbsp; When the FSLN was pressured by the contras, Cuba increased its assistance to Nicaragua.&nbsp; In 1983, for example, after the Contras scored some successes against the FSLN, Cuban general Arnoldo Ochoa traveled to Nicaragua to advice the Sandinistas on their military campaign, and the number of Cuban advisers and military units in Nicaragua increased dramatically.</p>
  <p><strong>The Soviet Union</strong><br />
    <br />
    The Sandinistas also maintained ties with the Soviet Union.&nbsp; According to Kagan, “By March of 1980, the Sandinistas had already signed a party-to-party agreement with the Soviet Communist Party, as well as secret military protocols to begin receiving arms from the Soviet bloc.&nbsp; Deliveries of Soviet weapons from Cuba began almost immediately thereafter.”&nbsp; Draper writes that the Sandinistas signed “economic, technical, scientific, and cultural agreements with the Soviet Union.” &nbsp;In 1982, the Soviets increased their financial and military support to the FSLN, and again in 1983 after the arrival of General Ochoa, when it provided tanks, transport trucks, helicopters, and other materiel.&nbsp; However, in 1984, while the Soviet Union was still giving a large amount of military aid, Soviet economic performance was on the decline, and the Soviets feared that they were losing the Cold War against the United States due to key strategic victories secured by the latter.&nbsp; The Sandinistas thus became worried that, in the future, Soviet support would decline.&nbsp; Despite robust aid during 1985, the Sandinistas believed that Soviet President Mikhail Gorbachev was less willing to support foreign revolutionary movements than previous Soviet leaders had been and that Soviet wishes to improve ties with the United States would hamper Soviet support.&nbsp; Sandinistas were heavily dependent on Soviet aid and oil; as Kagan notes, “The vital importance of close relations with the Soviet Union had been one of the few constants in Sandinista theory and policy since their earliest pre-revolutionary days.”<br />
  <br />
  The impetus for Nicaragua's ties with the Soviet Union is a matter of debate.&nbsp; Some argue that the Sandinistas sought relations with the Soviet Union only after the war with the contras and U.S. attempts to cut off Western aid to the Sandinistas made such relations necessary.&nbsp; Vanden writes, “After the first few years of Sandinista rule, problems with the United States, the contra war, the developing economic crisis, and the difficulties engendered in maintaining good relations with Western Europe combined to necessitate a cautious policy of engagement with the socialist countries.”&nbsp; In this view, it was the United States that was partially to blame for facilitating the Nicaraguan-Soviet relationship through the facilitation of armed rebellion in the country.&nbsp; On the other hand, Kagan argues that the Sandinistas had always intended to form an alliance with the Soviet Union and “actively sought” this alliance.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
  <p><strong>El Salvador</strong><br />
    <br />
    The Sandinistas also supported the spread of socialism abroad, most notably in nearby El Salvador.&nbsp; The FSLN sent weapons to leftist rebels in El Salvador, beginning no later than in mid-1980 and continuing for the next decade.&nbsp; Kagan argues that the FSLN supported the Salvadoran rebels “for reasons of ideology and affinity.”&nbsp; He also argues that the Sandinistas supported the rebels because they thought that, by aiding the rebels, they would convince the Soviet Union to fully support Nicaragua against U.S. intervention in the region and ensure that Nicaragua remained economically viable.&nbsp; Sandinista support for the Salvadoran rebels had a profound impact on U.S.-Nicaragua relations.&nbsp; </p>
  <div></div></div>
  <div align=center class="top_link"><p>[ <a href="#headertop">Return to top ]</a></p></div>
</div>


<? require ('templates/footer.php'); ?>