<? require ('templates/header.php'); ?>
<title>Understanding the Iran-Contra Affairs - The Legal Aftermath</title>
</head>
<? require ('templates/legalaftermathbanner.php'); ?>
    
<div style="margin: 10px 0px 0px 20px; width: 765px" align="justify" id="welcomenote">

<div align="left" class="bread_crumbs"><a href="profiles.php">Profiles</a>
&raquo; Ronald Reagan</div>


<h2>Ronald Reagan&nbsp;<font class="position">President</font></h2>

<p>Not only did the Iran-Contra Affairs occur entirely during his presidency, but the Affairs began only after President Ronald Reagan told his National Security Adviser Robert McFarlane to keep the Contras alive “body and soul” after the Boland Amendments had passed. Nevertheless, Walsh concluded that he could not prove beyond a reasonable doubt that the president knew the specific criminal elements of the Affairs or made criminal lies about what had occurred.</p>
<p>Specifically, investigators were unable to produce any evidence that Reagan approved or even knew of the private profits made through the sales to Iran or about the diversion of proceeds to the Contras. Although Walsh found it strange that Reagan would continue to allow these sales to go forward despite complications (Iran released few hostages and even changed the terms of negotiations) unless he knew the profits funded the Contras, National Security Adviser John Poindexter claimed to have kept him in the dark, and any possible contradictory evidence would have been lost when National Security Council staff member Oliver North destroyed official NSC documents.</p>
<p>Reagan was not totally unaware; he knew and endorsed the efforts to solicit financial support for the Contras from third-party countries and American citizens, and he knew that North was involved in that network. But that aspect of the Affairs was not criminal. The appeals he made personally were for humanitarian aid, and although he knew that money was funneled through the National Endowment for the Preservation of Liberty, there was no evidence he knew that NEPL violated the laws governing tax-exempt organizations.</p>
<p>Reagan’s own involvement with arms sales to Iran raised greater questions for Walsh. He was involved in supporting these sales through Israel and through the Central Intelligence Agency (disguised using businessmen Richard Secord and Albert Hakim’s Enterprise). Reagan specifically stated that officials should not tell Congress.</p>
<p>Walsh explained that this was directly in conflict with United States law:</p>
<p>There was no way in which President Reagan's action could be squared with the Arms Export Control Act (AECA). The AECA forbade the retransfer of U.S. arms to a third country unless the United States itself could make the transfer directly. It required certifications from the recipient country concerning further transfer. Finally, it required reports to the Speaker of the House and the Senate Foreign Relations Committee concerning retransfer agreements and notice to Congress 30 days after the end of each quarter of a transfer of more than $1 million of major defense equipment.</p>
<p>However, despite its strong language, the Arms Export Control Act did not provide for any criminal sanctions. This action could only be considered criminal in the event of a conspiracy to defraud the United States, such as was levied against North on account of hidden profits from the sales. Because Reagan could legitimately say that he was instead motivated by a desire for secrecy in order to protect the sensitive nature of the sales, as well as to save the hostages’ lives, Walsh felt a conspiracy charge was inappropriate.</p>
<p>Similarly, Section 501(a) of the National Security Act of 1947 demanded that the House and Senate intelligence committees be told about intelligence activities, except for those the President deemed especially sensitive; information about those could be limited to the committee chair and ranking member and the House and Senate leadership. However, Attorney General Edwin Meese III and the CIA general counsel had advised Reagan that he did not need to inform any member of Congress, something they claimed was implicit in “the introductory language of subsection (a), which is a lengthy expression of deference to the President's other duties and constitutional powers.”</p>
<p>Questions were also raised regarding Reagan’s role in the cover-up of the Affairs, again mostly stemming from the sales to Iran. Although he falsely denied that Eugene Hasenfus, whose Contra re-supply plane had crashed, was working with the U.S. Government, there is no evidence Reagan knew his claim was false. Poindexter told Reagan on October 7 that Hasenfus was not connected to them, and no evidence was found to show he learned otherwise at the time of these denials.</p>
<p>However, when the press and Congress began to ask questions in November 1986 after hearing of McFarlane’s travels to Iran and the arms-for-hostages deals, Reagan told part-truths and worked with others in his administration to continue to hide politically damaging information.</p>
<p>That month, the White House briefed congressional leaders, but the timeline that Reagan offered them left out the 1985 Israeli shipments. Moreover, even though he was present, he did not correct the false claim to those congressional leaders that his “Finding preceded all arms shipments.” Finally, although no one claimed that Reagan worked with Poindexter and CIA Director William Casey to prepare their false testimony, truthful testimony would have been inconsistent with Reagan’s own statements.</p>
<p>However, regarding this deception, Walsh ultimately concluded:</p>
<p>The question of whether the President, in the discharge of his constitutional office, is criminally liable for false statements and obstruction of congressional inquiries regarding his activities is not a ready field for criminal prosecution. The President is quite different from any subordinate in his relationship with Congress. But the fundamental reason for lack of prosecutorial effort was the absence of proof beyond a reasonable doubt that the President knew that the statements being made to Congress were false, or that acts of obstruction were being committed by Poindexter, North and others.</p>
<p>Reagan interacted with Walsh’s office a number of times. He provided sworn, written answers to the Independent Counsel’s and the grand jury’s questions, testified during National Security Adviser John Poindexter’s trial, and provided a deposition in 1992. There was nothing to suggest that he ever made false statements or committed perjury, and although he professed to be unable to recall much and often gave vague answers, it was also clear by his final deposition that his memory of even major Iran-Contra related events was incomplete. Ultimately, for the reasons given above, Walsh decided not to bring any charges against Reagan.</p>
</div><? require ('templates/footer.php'); ?>