<? require ('templates/header.php'); ?>
<title>Understanding the Iran-Contra Affairs - The Legal Aftermath</title>
</head>
<? require ('templates/legalaftermathbanner.php'); ?>
    
<div style="margin: 10px 0px 0px 20px; width: 765px" align="justify" id="welcomenote">

<div align="left" class="bread_crumbs"><a href="profiles.php">Profiles</a>
&raquo; Richard Armitage</div>


<h2>Richard Armitage&nbsp;<font class="position">Assistant Secretary of Defense for International Security Affairs</font></h2>

<p>As assistant secretary of defense for international security affairs from May of 1983 until January of 1989, Richard Armitage was one of Secretary of Defense Caspar Weinberger’s closest advisers and spoke with him daily. He also maintained strong relationships with officials in other defense and intelligence-related agencies.</p>
<p>In testimony before the Senate Select Committee on Intelligence in December of 1986, Armitage claimed that he did not know Israel had shipped TOW and HAWK missiles to Iran in August, September, and November 1985 until Central Intelligence Agency Director William Casey’s testimony in November 1986 that the U.S. had replenished their missile stocks. However, National Security Council staff member Oliver North documented a discussion with Armitage about the sales days before Casey’s testimony.</p>
<p>Moreover, on December 2, 1985, Armitage had met with a group of officials involved in the sales: North, Israeli General Menachem Meron, and Enterprise businessman Richard Secord. Armitage’s own records indicated three separate contacts with Meron, but he still claimed that Meron had given him “no hard information” about shipments to Iran.</p>
<p>Despite his claims, one of North’s notes makes clear that Meron was actively discussing these sales with U.S. officials along with Israel’s desire to have its stocks replenished. Secord recalled specifically telling Meron to discuss the replenishment with Armitage.</p>
<p>In addition, Armitage’s records show that he had met with Secord on December 5 and on December 27, but claimed not to recall the meetings. Walsh explained that his comments regarding these meetings were inconsistent. In December of 1986, he told the FBI he did not know of Secord’s role in sales to Iran. Just eight days later, he said that he had found out months earlier that Secord was working with North. Secord, on the other hand, repeatedly claimed that he met with Armitage to (unsuccessfully) convince him to urge Weinberger to support the sales, which the two opposed.</p>
<p>Walsh also uncovered substantial circumstantial evidence that Armitage read one of North’s papers, which included detailed and explicit information on past Israeli sales to Iran and about the possibilities for additional deals, on December 5 or December 6 1985. While there is no doubt that Armitage and Weinberger read that document eventually, since Armitage placed it in a briefing book for Weinberger in November of 1986 before he met with President Reagan, Armitage’s call logs and records of meetings with North indicate that he likely received it on one of those days in December. This is especially likely because the paper related to his meetings with Meron, and because Secretary of State George Shultz spoke with North about the paper; it would have been counterintuitive for North to speak with Shultz but not with the Department of Defense, which controlled the U.S. missile stocks.</p>
<p>Finally, there were concerns regarding Armitage’s testimony about the preparations made in advance of Weinberger’s White House meeting in December 1985. He said that he prepared his boss “orally without any paper trail.” However, in 1987, the Department of Defense gave Walsh and Congress two papers about sales to Iran that had been prepared by Defense employees around that time. Armitage admitted that it was likely he had given them to Weinberger or had at least summarized them for him.</p>
<p>Ultimately, Walsh did not prosecute Armitage. First, Armitage said that he had told one of his aides to review his files and provide investigators with any relevant material, a claim the aide corroborated. Thus, it was unlikely Walsh could successfully prosecute him for the non-production or belated production of any documents. Walsh also did not believe that he could prove that Armitage's false testimony was deliberate beyond a reasonable doubt, as opposed to potentially misremembered or mistaken.</p>
</div><? require ('templates/footer.php'); ?>