<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<link href="../templates/main2.css" rel="stylesheet" type="text/css" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</head>
<body>
<div style="width:325px"><font class="transcript">

<br/><br/><strong>Mr. LIMAN</strong>:  Did you ever look and see the bank records before
you met in the committee rooms here?
<br/><br/><strong>Mr. SECORD</strong>:  No, I have never seen the bank records.
<br/><br/><strong>Mr. LIMAN</strong>:  Did you ever ask to see the bank records?
<br/><br/><strong>Mr. SECORD</strong>:  No.
<br/><br/><strong>Mr. LIMAN</strong>:  Did you ever sign any document that gave you access
to the bank records?
<br/><br/><strong>Mr. SECORD</strong>:  Never.
<br/><br/><strong>Mr. LIMAN</strong>:  Why did you choose not to ask Hakim to see the
bank records?
<br/><br/><strong>Mr. SECORD</strong>:  I didn't think they were important.
<br/><br/><strong>Mr. LIMAN</strong>:  Did you not think it was important to know how
much money there was that was generated by this enterprise?
<br/><br/><strong>Mr. SECORD</strong>:  He was telling me. I knew what the deposits were.
<br/><br/><strong>Mr. LIMAN</strong>:  And you knew what the expenditures were?
<br/><br/><strong>Mr. SECORD</strong>:  Generally.
<br/><br/><strong>Mr. LIMAN</strong>:  Now even after you told Hakim that you didn't want
the interest in the profits, were you controlling the expenditures?
<br/><br/><strong>Mr. SECORD</strong>:  I was directing him to make the expenditures in
support of the various projects.
<br/><br/><strong>Mr. LIMAN</strong>:  Is it a fact, Mr. Secord, that after August 1985, all of
the funds that were generated in those bank accounts came from
your efforts?
<br/><br/><strong>Mr. SECORD</strong>:  Yes.
<br/><br/><strong>Mr. LIMAN</strong>:  And is it a fact that all of the expenditures were expenditures that you directed expensed?
<br/><br/><strong>Mr. SECORD</strong>:  The general answer to that question is yes. However, I would like to qualify the answer by saying Mr. Hakim probably made some expenditures from his profits that I would have no
idea of.
<br/><br/><strong>Mr. LIMAN</strong>:  Now, did you know what his profits were?
<br/><br/><strong>Mr. SECORD</strong>:  Generally.
<br/><br/><strong>Mr. LIMAN</strong>:  And was Mr. Hakim to receive a profit on the sale of
the weapons to Iran?
<br/><br/><strong>Mr. SECORD</strong>:  No.
<br/><br/><strong>Mr. LIMAN</strong>:  And was that because you and he agreed that that
would be done on a non-profit basis?
<br/><br/><strong>Mr. SECORD</strong>:  That is correct.
<br/><br/><strong>Mr. LIMAN</strong>:  And the profits from the Iran sale were to be dedicated to another purpose. Am I correct?
<br/><br/><strong>Mr. SECORD</strong>:  That is correct.
<br/><br/><strong>Mr. LIMAN</strong>:  And is it a fact that you told Oliver North that you
would not be making profits from the Iran sale?
<br/><br/><strong>Mr. SECORD</strong>:  I did not tell him that.
<br/><br/><strong>Mr. LIMAN</strong>:  Did you tell him that you would be making profits?
<br/><br/><strong>Mr. SECORD</strong>:  I didn't tell him anything about it.
<br/><br/><strong>Mr. LIMAN</strong>:  He never asked you?
<br/><br/><strong>Mr. SECORD</strong>:  No, he knew it was a commercial enterprise. He assumed we were making some money.
<br/><br/><strong>Mr. LIMAN</strong>:  But between you and Hakim, you agreed that you
would make no profit?
<br/><br/><strong>Mr. SECORD</strong>:  On those transactions, that is correct.
<br/><br/><strong>Mr. LIMAN</strong>:  And is there any other occasion that you can think
of where Mr. Hakim decided to go into a commercial venture for
no profit?
<br/><br/><strong>Mr. SECORD</strong>:  No. But he was already making profits in the arms
sales, and I thought that was fair enough.
<br/><br/><strong>Mr. LIMAN</strong>:  Well, the profits that he was making in the arms
sales were the sales to Calero, right?
<br/><br/><strong>Mr. SECORD</strong>:  The contra.
<br/><br/><strong>Mr. LIMAN</strong>:  And those sales amounted to what, about 10, $11 million?
<br/><br/><strong>Mr. SECORD</strong>:  That is what we added up the other day, yes.
<br/><br/><strong>Mr. LIMAN</strong>:  And you said that the mark-up on those was about
average—averaged about 20 percent, correct?
<br/><br/><strong>Mr. SECORD</strong>:  That is correct.
<br/><br/><strong>Mr. LIMAN</strong>:  So that the profits on those would have been about,
gross, about $2 million?
<br/><br/><strong>Mr. SECORD</strong>:  Hakim calculated those profits. It was in that range,
and I don't have exact numbers.
<br/><br/><strong>Mr. LIMAN</strong>:  Of those $2 million, some of it was originally allocated to you, correct?
<br/><br/><strong>Mr. SECORD</strong>:  Originally, yes.
<br/><br/><strong>Mr. LIMAN</strong>:  Half of it?
<br/><br/><strong>Mr. SECORD</strong>:  No, nothing like that.
<br/><br/><strong>Mr. LIMAN</strong>:  Some of it to Mr. Clines?
<br/><br/><strong>Mr. SECORD</strong>:  Yes.
<br/><br/><strong>Mr. LIMAN</strong>:  And after what was allocated to Clines, the balance
was allocated half to you and half to Hakim originally?
<br/><br/><strong>Mr. SECORD</strong>:  Except that some payments were made to Mr. Quintero for his efforts.
<br/><br/><strong>Mr. LIMAN</strong>:  And after that expense, the rest was divided between
you and the
<br/><br/><strong>Mr. SECORD</strong>:  Just as we have said about four times now.
<br/><br/><strong>Mr. LIMAN</strong>:  And no profits of the $15 million that you have testified the other day from the Iran sale were to be kept by Hakim or
you? Correct?
<br/><br/><strong>Mr. SECORD</strong>:  The number is 14 million, and that is correct.
<br/><br/><strong>Mr. LIMAN</strong>:  Isn't the $14 million exclusive of the million dollars
you received from Israel in November?
<br/><br/><strong>Mr. SECORD</strong>:  I accounted for that in my testimony.
<br/><br/><strong>Mr. LIMAN</strong>:  Isn't the $14 million exclusive of that million?
<br/><br/><strong>Mr. SECORD</strong>:  Exclusive of that $800,000, yes.
<br/><br/><strong>Mr. LIMAN</strong>:  Well, whether it is $14 million or $14,800,000, your
testimony here today was Hakim was not to keep any of that?
<br/><br/><strong>Mr. SECORD</strong>:  That is right. And I think the bank records show
that, as you must be aware by now.
<br/><br/><strong>Mr. LIMAN</strong>:  And the $8 million that is now in some bank account
really is not money that belongs to Hakim or you; is that correct?
<br/><br/><strong>Mr. SECORD</strong>:  Well, the counsel—would you restate the question,
please, sir?
<br/><br/><strong>Mr. LIMAN</strong>:  Where is the $8 million that is being held today
under the control of Mr. Hakim?
<br/><br/><strong>Mr. SECORD</strong>:  The House counsel read that into the record, and as
far as I know, it is correct.
But he
<br/><br/><strong>Mr. LIMAN</strong>:  Where is it?
<br/><br/><strong>Mr. SECORD</strong>:  There is something over a million in a Swiss bank
account, and the balance, according to Mr. Hakim's testimony, is
being held by a fiduciary on his behalf.
<br/><br/><strong>Mr. LIMAN</strong>:  What is the name of the fiduciary who is holding it?
<br/><br/><strong>Mr. SECORD</strong>:  I don't have any idea.
<br/><br/><strong>Mr. LIMAN</strong>:  In what bank?
<br/><br/><strong>Mr. SECORD</strong>:  I have no idea.
<br/><br/><strong>Mr. LIMAN</strong>:  You never asked him?
<br/><br/><strong>Mr. SECORD</strong>:  I did, but there is no communication on that point.
<br/><br/><strong>Mr. LIMAN</strong>:  But that is money that was generated by the Iranian
arms sale, correct?
<br/><br/><strong>Mr. SECORD</strong>:  Correct.
<br/><br/><strong>Mr. LIMAN</strong>:  And on the basis of your testimony, that is money
that doesn't belong to Mr. Hakim, correct?
<br/><br/><strong>Mr. SECORD</strong>:  I didn't say that. I said that in my testimony, that
the money is the money of the enterprise.
<br/><br/><strong>Mr. LIMAN</strong>:  The money is the money of the enterprise, and who
owns the enterprise?
<br/><br/><strong>Mr. SECORD</strong>:  Mr. Hakim is the technical owner.
<br/><br/><strong>Mr. LIMAN</strong>:  And is there a beneficial owner other than Mr.
Hakim?
<br/><br/><strong>Mr. SECORD</strong>:  No.
<br/><br/><strong>Mr. LIMAN</strong>:  So, Mr. Hakim is both the technical owner and the
beneficial owner?
<br/><br/><strong>Mr. SECORD</strong>:  That is correct.
<br/><br/><strong>Mr. LIMAN</strong>:  And yet you said a moment ago that Hakim was not.
to get any of the profits out of the Iranian arms sale?
<br/><br/><strong>Mr. SECORD</strong>:  That was our plan.
<br/><br/><strong>Mr. LIMAN</strong>:  So that the $8 million that is out there now is just
being kept, but it isn't profit?
<br/><br/><strong>Mr. SECORD</strong>:  That is a different issue, Mr. Liman, as you well
know.
In the first place, there are many bills that have yet to be paid
outstanding against this enterprise. Bills that have to be paid. I
don't know how much is going to be left after these bills are paid,
and I am not focusing on that right now. I have got bigger problems to focus on than that.
I have got a special prosecutor over here across the street that is
trying to throw all of us in jail for performing our duty as we saw
it.
I haven't focused on some technical issue like you are bringing
up here. This is crazy.
<br/><br/><strong>Mr. LIMAN</strong>:  Was it part of your duty to keep this $8 million?
<br/><br/><strong>Mr. SECORD</strong>:  Of course it was part of our duty to keep the $8 million. We had it in there for operating revenue. I didn't terminate
this operation; the operation was blown apart. The operation was
aborted:
<br/><br/><strong>Mr. LIMAN</strong>:  So is it
<br/><br/><strong>Mr. SECORD</strong>:  That was a snapshot that existed at that time.
<br/><br/><strong>Mr. LIMAN</strong>:  Is what you are saying you expected if the arms sales
continued to go forward, you would need to use this money to keep
the enterprise going?
<br/><br/><strong>Mr. SECORD</strong>:  Correct.
<br/><br/><strong>Mr. LIMAN</strong>:  So that the enterprise could continue as a vehicle for
the Iranian arms sales?
<br/><br/><strong>Mr. SECORD</strong>:  That is correct.
<br/><br/><strong>Mr. LIMAN</strong>:  Isn't it a fact, Mr. Secord, that in the case of every
sale of arms that you made to Iran, you got paid by Ghorbanifar
before you paid any money out to the CIA?
<br/><br/><strong>Mr. SECORD</strong>:  No.
<br/><br/><strong>Mr. LIMAN</strong>: Is there an instance that you can recall where you didn't get the money up front?
<br/><br/><strong>Mr. SECORD</strong>: No, you said by Ghorbanifar. In the October transaction, we were paid by the Iranian government.
<br/><br/><strong>Mr. LIMAN</strong>:  OK. You are a very literal man, so let me be literal,
too. In every instance of sales to Iran, you received the money up
front before you laid it out to
<br/><br/><strong>Mr. SECORD</strong>:  Yes, sir.
<br/><br/><strong>Mr. LIMAN</strong> [continuing]. The U.S. Government.
<br/><br/><strong>Mr. SECORD</strong>:  Correct. Correct.
<br/><br/><strong>Mr. LIMAN</strong>:  And is it true that in every instance the amount that
you received up front exceeded what the cost was, charged by the
CIA and the transportation cost?
<br/><br/><strong>Mr. SECORD</strong>:  Correct.



</font></div>
</body>
</html>
